### ISSUE TITLE
Material color scheme is changed

### ISSUE THREAD

**Issue by benedict1986** [BhavinPatel04/ngx-datetime-range-picker#10]
Hi, thank you for such nice library. However when I use it, it changes my color scheme. My primary color is purple but it is changed to blue when I use color='primary'. Is there an easy way to not change the color scheme. Thanks

**Comment by BhavinPatel04** [comment]
Aha.. I think because the library has its own theme.
Thank you for the feedback. Will fix this!

**Comment by benedict1986** [comment]
Thanks a lot.

**Comment by BhavinPatel04** [comment]
Hey, I finally made the library to accept dynamic theme. Please update to v2.0.0 and refer [Installation](https://github.com/BhavinPatel04/ngx-datetime-range-picker#installation)
