### ISSUE TITLE
Unable to use Component in sub-modules - 'unknown element' / 'already imported'

### ISSUE THREAD

**Issue by mmolle-nelo** [BhavinPatel04/ngx-datetime-range-picker#11]
Hi,

I'm currently not able to import and use this component inside sub components inside my Angular 7 project.

After adding `NgxDatetimeRangePickerModule.forRoot()` to the `import`-section of `app.module.ts`, the component is only available on the top-level `AppComponent`, but not on any child components such like sub-pages. (error message from Angular compiler: `'ngx-datetime-range-picker' is not a known element`

By importing the `NgxDatetimeRangePickerModule` inside a custom lazy-loaded sub-module for handling date range picker on multiple places, the NgxDatetimeRangePickerModule throws an error: `NgxDatetimeRangePickerModule is already loaded. Import it in the AppModule only`.

What is needed here to properly use NgxDatetimeRangePickerModule inside a custom lazy-loaded component?

Thanks,
Martin

**Comment by BhavinPatel04** [comment]
@mmolle-nelo 
1st issue: Is there any way that I can take a look at the repo?

2nd issue:
You can create a small wrapper module in application code-base (example: ngx-datetime-range-picker-wrapper.module) and then import it using `./ngx-datetime-range-picker-wrapper.module#NgxDatetimeRangePickerModule`. I didn't get enough time to try this myself but please let me know if this works for you.

**Comment by BhavinPatel04** [comment]
Closing it due to inactivity. Please feel free to reopen it.

**Comment by MayurMudliar** [comment]
reopening bcoz it does not work in submodules
