### ISSUE TITLE
Date range lable extraction

### ISSUE THREAD

**Issue by prashantmahake** [BhavinPatel04/ngx-datetime-range-picker#13]
As I can see in the demo, there are various labels to select from i.e last 7 days, last week and so on.
I just wanted to know if there is any way to extract those labels, in to a variable on selection.
for eg. if I select last 7 days while selecting a range, then I want "last 7 days" as string in my variable so that i can use that label for further processing.
I was just curious about is there any work around for that or is there any way to achieve this?
![Screenshot from 2019-11-19 17-41-26](https://user-images.githubusercontent.com/57946454/69145583-fb706800-0af3-11ea-91f7-786ede1eb9dd.png)

I forked your repo in my own project and tried modifying it, but it failed. I did install plugin from npm, and what is observed is structure of that plugin and your code is different. 

```
 onRangeClick(rangeLabel: string, dateRangeModel: Options) {
    this.state.activeRange = rangeLabel;
    if (rangeLabel === "Custom Range") {
      this.state.customRange = true;
    } else {
      this.state.customRange = false;
      this.config.startDate = dateRangeModel.startDate;
      this.config.endDate = dateRangeModel.endDate;
      if (this.config.timePicker) {
        this.state.times = {};
      }
      this.setActiveItemOnRangeClick();
    }
  }
```

this is the function is get called when you click on label, all i want is range label. Can you tell me how can i achieve this by forking your repo.
Thanks in advance

**Comment by BhavinPatel04** [comment]
Hey @prashantmahake, thank you using this library! Appreciate it!

There are 2 ways to achieve what you want:
- Get the label in your app:
You can create an rangeObject and pass it to the `availableRanges` prop in settings. Then in `dateRangeChanged` callback you can iterate over that rangeObject and get the selected label based on startDate and endDate
- Make changes in the lib code:
You would need to add `activeRange` prop in the `Options` interface (`activeRange?: string`) and emit it in the `dateRangeChanged`. You can access `activeRange` from the state via `this.state.activeRange`.

Although this is a good use-case and others might benefit from this as well. If you can wait, I can make this change over this weekend and release it. Then you can use it out of the box. :)

Can you please elaborate what you mean by structure is different? I am curious about it.

Let me know if you have any other questions.

**Comment by BhavinPatel04** [comment]
Added `activeRange` to output. Please update to `2.0.2`.

**Comment by prashantmahake** [comment]
Thanks Bhavin for such a quick response, appreciate it !!

**Comment by jamalmehmood** [comment]
@BhavinPatel04 Is there any option through which I can make my own custom buttons?
Like in above screen @prashantmahake has shared an image having last 7 days, last 30 days, last 90 Days,
instead, I want buttons like last 6 hours, Last 24 hours, today and tomorrow.
