### ISSUE TITLE
Existing code doesn't rum

### ISSUE THREAD

**Issue by eklavyalodha** [BhavinPatel04/ngx-datetime-range-picker#14]
Existing code doesn't rum

**Comment by BhavinPatel04** [comment]
@eklavyalodha the existing code seems to be working on https://bhavinpatel04.github.io/ngx-datetime-range-picker/. 

Can you please elaborate your issue? How are you including the library and some error details.

**Comment by BhavinPatel04** [comment]
Closing this since there is no update on this issue. Please feel free to reopen it.
