### ISSUE TITLE
scss?

### ISSUE THREAD

**Issue by ramtob** [BhavinPatel04/ngx-datetime-range-picker#16]
Hello. The readme file says: 

> Add below config in your style.scss/some-cool-name-theme.scss, which has material theme (or not) and is imported in your angular.json
> 
> @import "ngx-datetime-range-picker/ngx-datetime-range-picker.theme.scss";
> @include ngx-datetime-range-picker-theme($app-theme);

What if I don't use .scss files in my project?
(but .css, or .less, etc?)

**Comment by ramtob** [comment]
P.S. If you want to provide extra options to .scss users, I think that is reasonable. But it it not reasonable to require that the user of this component will have to use .scss files. The basic styles need to be provided as .css file, and this should be sufficient for using the component. For extra control the user may have to use .scss. But not for basic use. Thanks.

**Comment by BhavinPatel04** [comment]
@ramtob Your suggestion completely makes sense and I am already working on it whenever I get enough time from work.
I started with .scss because I was actually using .scss in my project in which I needed this feature.
Will update this thread once I am done with it.

**Comment by ramtob** [comment]
@BhavinPatel04 Thanks for the update. I think that this issue should stay open, because it is not resolved (that is, neither solved nor rejected).

**Comment by BhavinPatel04** [comment]
@ramtob Done. You can now .css in the project. Please feel free to reopen if you want .less as well.

https://github.com/BhavinPatel04/ngx-datetime-range-picker#css

**Comment by ramtob** [comment]
> @ramtob Done. You can now .css in the project. Please feel free to reopen if you want .less as well.
> 
> https://github.com/BhavinPatel04/ngx-datetime-range-picker#css

@BhavinPatel04  Very nice, thanks.
