### ISSUE TITLE
Error Angular 9.1.6

### ISSUE THREAD

**Issue by z3v0k** [BhavinPatel04/ngx-datetime-range-picker#19]
Compiling ngx-datetime-range-picker : es2015 as esm2015
Error: Failed to compile entry-point ngx-datetime-range-picker (es2015 as esm2015) due to compilation errors:
node_modules/ngx-datetime-range-picker/fesm2015/ngx-datetime-range-picker.js:1776:18 - error NG1010: Value at position 0 in the NgModule.imports of MaterialModule is not a reference: [object Object]

1776         imports: modules,

Help me. thanks!

**Comment by russnewport** [comment]
Having the same problem with Angular version 9.0.7.

**Comment by BhavinPatel04** [comment]
@z3v0k Fixed! Please update to v3.0.1
