### ISSUE TITLE
custom predefined range buttons

### ISSUE THREAD

**Issue by jamalmehmood** [BhavinPatel04/ngx-datetime-range-picker#22]
@BhavinPatel04 Is there any option through which I can make my own custom buttons?
Like in the attached screen it is last 7 days, last 30 days, last 90 days,
instead, I want buttons like last 6 hours, Last 24 hours, today and tomorrow.
![image](https://user-images.githubusercontent.com/12895771/87037457-ad84ad80-c205-11ea-9d93-97c376c67057.png)

**Comment by BhavinPatel04** [comment]
@jamalmehmood Yes, you can. Use availableRanges properties in settings.
https://github.com/BhavinPatel04/ngx-datetime-range-picker#settings
