### ISSUE TITLE
Does not work with Angular 6

### ISSUE THREAD

**Issue by MayurMudliar** [BhavinPatel04/ngx-datetime-range-picker#29]
![image](https://user-images.githubusercontent.com/40629150/96988510-0de3f480-1542-11eb-83c5-928a88c1c880.png)

I get this

and this on the console:-

![image](https://user-images.githubusercontent.com/40629150/96988683-45eb3780-1542-11eb-9983-756f49f77f44.png)

**Comment by BhavinPatel04** [comment]
I will try to find a permanent solution for this issue as soon as get some time off work. In the meantime, can you try updating angular core if possible? 
```
ng update @angular/core -f
```

**Comment by BhavinPatel04** [comment]
`ngx-datetime-range-picker@v4.0.0` and it will run on the latest angular version - v@17.0.0
