### ISSUE TITLE
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module

### ISSUE THREAD

**Issue by glenndierckx** [BhavinPatel04/ngx-datetime-range-picker#4]
So when lazy loading, I receive this error message. Can the BrowserModule be removed from the library?

**Comment by BhavinPatel04** [comment]
Sorry for the delay! Please pull the latest version **1.1.3**

Have included **NoopAnimationsModule** instead. Please reopen if you still have issues!
