### ISSUE TITLE
Issue in date-range-picker

### ISSUE THREAD

**Issue by EVNIKHIL** [BhavinPatel04/ngx-datetime-range-picker#51]
I was playing with the demo from https://bhavinpatel04.github.io/ngx-datetime-range-picker/ date range picker the last one. I found there are some issue in date time range picker
1. When we try to set minute in the calendar it not populating every time.
2. Event if set the time and apply the date. The place holder in the date picker is not correct. it shows '18:minute' even if we selected 18:30

**Comment by troyunzio** [comment]
Any update on this ? @BhavinPatel04  @EVNIKHIL

**Comment by BhavinPatel04** [comment]
@EVNIKHIL @troyunzio I've fixed this issue in `3.1.0`. I apologize for taking it so long to address this issue.

Please upgrade to version `3.1.0`.
